# SI 370 - Homework #1: Data Manipulation and Preliminary Analyses


## Background


This homework assignment focuses on the exploration and analysis of data science job salaries.


Your main task in this assignment is to explore the data _using the data
manipulation and analysis methods we covered in class_ as well as those in the assigned readings. You may need to consult pandas documentation, Stack Overflow, or other online resources.


Question 1 is worth 10% of the points, the remaining 90% of points is distributed evenly over the remaining questions. Points will be allocated according to the following rubric:

- 90-100%: Question is correctly and completely answered. Answer consists of well-written code that conforms to [PEP 8](https://www.python.org/dev/peps/pep-0008/) guidelines and is
  accompanied by a written interpretation in a Markdown block. Written interpretation does not contain spelling, grammar or stylistic errors (see [Strunk & White](https://drive.google.com/file/d/1L0P7xJwjUGBvyb49mL3dw1Bt7hzRTiTl/view?usp=sharing) for a detailed specifications). Minor problems, such as formatting, incorrect submissions, missing names, etc. will result in less than 100%.
- 75-85% : Answer is mostly complete and correct; two or fewer noticeable omissions or errors. Minor stylistic flaws, either in code or in
  written interpretation.
- 50-70%: Answer has significant omissions or errors; Noticeable departure from PEP-8 guildelines and/or moderate spelling, grammar, or style issues
  in written interpretations.
- 25-45%: Question is perfunctorily attempted. Substantial parts are missing or incorrect.
- 0 points: Question not attempted.


## First, Download the data (ds_salaries.csv) from:

- https://www.kaggle.com/datasets/ruchi798/data-science-job-salaries

(Note: you will also find a description of the dataset at that URL.)


## Answer the questions below.

For each question, you should

1. Write code using Python and pandas that can help you answer the following questions, and
2. Explain your answers in plain English. You should use complete sentences that would be understood by an educated professional who is not necessarily a data scientist (like a product manager).


In [106]:
import pandas as pd


### Q1: Load and describe the dataset

- Choose the value of the index carefully -- you should not have an extra column called "Unnamed: 0"
- How many number rows and columns are there in the data frame?
- Provide summary statistics (i.e. use the .describe() function) for the numeric and categorical variables (you can ignore the ID column).


In [107]:
# put your code here

salaries = pd.read_csv('../data/ds_salaries.csv', index_col='Unnamed: 0')


In [108]:
salaries


work_year experience_level employment_type                   job_title  \
0         2020               MI              FT              Data Scientist   
1         2020               SE              FT  Machine Learning Scientist   
2         2020               SE              FT           Big Data Engineer   
3         2020               MI              FT        Product Data Analyst   
4         2020               SE              FT   Machine Learning Engineer   
..         ...              ...             ...                         ...   
602       2022               SE              FT               Data Engineer   
603       2022               SE              FT               Data Engineer   
604       2022               SE              FT                Data Analyst   
605       2022               SE              FT                Data Analyst   
606       2022               MI              FT                AI Scientist   

     salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0     70000             EUR          79833                 DE             0   
1    260000             USD         260000                 JP             0   
2     85000             GBP         109024                 GB            50   
3     20000             USD          20000                 HN             0   
4    150000             USD         150000                 US            50   
..      ...             ...            ...                ...           ...   
602  154000             USD         154000                 US           100   
603  126000             USD         126000                 US           100   
604  129000             USD         129000                 US             0   
605  150000             USD         150000                 US           100   
606  200000             USD         200000                 IN           100   

    company_location company_size  
0                 DE            L  
1                 JP            S  
2                 GB            M  
3                 HN            S  
4                 US            L  
..               ...          ...  
602               US            M  
603               US            M  
604               US            M  
605               US            M  
606               US            L  

[607 rows x 11 columns]

In [109]:
salaries.shape


(607, 11)

In [110]:
salaries.describe(include="all")


work_year experience_level employment_type       job_title  \
count    607.000000              607             607             607   
unique          NaN                4               4              50   
top             NaN               SE              FT  Data Scientist   
freq            NaN              280             588             143   
mean    2021.405272              NaN             NaN             NaN   
std        0.692133              NaN             NaN             NaN   
min     2020.000000              NaN             NaN             NaN   
25%     2021.000000              NaN             NaN             NaN   
50%     2022.000000              NaN             NaN             NaN   
75%     2022.000000              NaN             NaN             NaN   
max     2022.000000              NaN             NaN             NaN   

              salary salary_currency  salary_in_usd employee_residence  \
count   6.070000e+02             607     607.000000                607   
unique           NaN              17            NaN                 57   
top              NaN             USD            NaN                 US   
freq             NaN             398            NaN                332   
mean    3.240001e+05             NaN  112297.869852                NaN   
std     1.544357e+06             NaN   70957.259411                NaN   
min     4.000000e+03             NaN    2859.000000                NaN   
25%     7.000000e+04             NaN   62726.000000                NaN   
50%     1.150000e+05             NaN  101570.000000                NaN   
75%     1.650000e+05             NaN  150000.000000                NaN   
max     3.040000e+07             NaN  600000.000000                NaN   

        remote_ratio company_location company_size  
count      607.00000              607          607  
unique           NaN               50            3  
top              NaN               US            M  
freq             NaN              355          326  
mean        70.92257              NaN          NaN  
std         40.70913              NaN          NaN  
min          0.00000              NaN          NaN  
25%         50.00000              NaN          NaN  
50%        100.00000              NaN          NaN  
75%        100.00000              NaN          NaN  
max        100.00000              NaN          NaN

There are 607 rows and 11 columns in the salaries data frame. From the describe function, we can see that the meam salary in USD is $112,297.87.


### Q2: How many countries (based on employee residence) are represented by at least 10 individuals in the dataset, and what are they?

Be sure to use the complete country name, not just the two-letter abbreviation. You can do this manually, or you can check out the `pycountry` module.


In [111]:
# put your code here

value_counts = salaries["employee_residence"].value_counts()

filtered_counts = value_counts[value_counts >= 10]

filtered_counts.size


8

In [124]:
country_mapping = {'CA': 'Canada', 'DE': 'Germany', 'ES': 'Spain', 'FR': 'France',
                   'GB': 'Great Britain', 'GR': 'Greece', 'IN': 'India', 'US': 'United States'}

filtered_counts.index.map(country_mapping)


Index(['United States', 'Great Britain', 'India', 'Canada', 'Germany',
       'France', 'Spain', 'Greece'],
      dtype='object')

There are 8 countries who are represented by at least 10 individuals in the dataset including the United States, Great Britain, India, Canada, Germany, France, Spain, and Greece.


### Q3: Which job title has the highest median salary?


In [113]:
# put your code here

salaries.groupby("job_title").salary_in_usd.median(
).sort_values(ascending=False).head(1).index


Index(['Data Analytics Lead'], dtype='object', name='job_title')

The job title that has the highest median salary is a Data Analytics Lead.


### Q4: Which country, based on the company location, has the highest median salary?


In [114]:
# put your code here

salaries.groupby("company_location").salary_in_usd.median().sort_values(
    ascending=False).head(1).index.map({"RU": "Russia"})


Index(['Russia'], dtype='object', name='company_location')

The company location of the highest median salary is Russia.


### Q5: What proportion of employees live in the same country as the company they work for?


In [115]:
# put your code here

(salaries['employee_residence'] == salaries['company_location']).mean()


0.9159802306425041

91.589% of employees live in the same country as the company that they work for. There is a fairly high percentage.


### Q6:

Create four "bins" for salary such that 25% of the values fall in each bin (i.e. create quartiles). (Hint: check out pd.qcut())

Create a crosstab (or pivot table) showing the number of individuals for each combination of salary bin and experience level.


In [116]:
# put your code here

salaries["quartiles"] = pd.qcut(
    salaries['salary_in_usd'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])


In [117]:
salaries


work_year experience_level employment_type                   job_title  \
0         2020               MI              FT              Data Scientist   
1         2020               SE              FT  Machine Learning Scientist   
2         2020               SE              FT           Big Data Engineer   
3         2020               MI              FT        Product Data Analyst   
4         2020               SE              FT   Machine Learning Engineer   
..         ...              ...             ...                         ...   
602       2022               SE              FT               Data Engineer   
603       2022               SE              FT               Data Engineer   
604       2022               SE              FT                Data Analyst   
605       2022               SE              FT                Data Analyst   
606       2022               MI              FT                AI Scientist   

     salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0     70000             EUR          79833                 DE             0   
1    260000             USD         260000                 JP             0   
2     85000             GBP         109024                 GB            50   
3     20000             USD          20000                 HN             0   
4    150000             USD         150000                 US            50   
..      ...             ...            ...                ...           ...   
602  154000             USD         154000                 US           100   
603  126000             USD         126000                 US           100   
604  129000             USD         129000                 US             0   
605  150000             USD         150000                 US           100   
606  200000             USD         200000                 IN           100   

    company_location company_size quartiles  
0                 DE            L        Q2  
1                 JP            S        Q4  
2                 GB            M        Q3  
3                 HN            S        Q1  
4                 US            L        Q3  
..               ...          ...       ...  
602               US            M        Q4  
603               US            M        Q3  
604               US            M        Q3  
605               US            M        Q3  
606               US            L        Q4  

[607 rows x 12 columns]

In [118]:
pt = salaries.pivot_table(index="experience_level",
                          values="salary_in_usd", aggfunc="count", columns="quartiles")


In [119]:
pt


quartiles         Q1  Q2  Q3   Q4
experience_level                 
EN                50  28   8    2
EX                 0   4   7   15
MI                80  67  43   23
SE                23  52  98  107

From the pivot table above, we can see the number of individuals that fall within each experience level and salary quartile. Most prominently, we can see the most indiviuals from the data set (107) have senior experience and are in the Q4 quartile for salary. Conversely, we see that 0 individuals from the data set are executives within the first salary quartile.


### Q7:

Using only those rows that represent individuals from countries for which there are at least 10 people in the dataset, create a dataframe that consists of one column per country and one row per job title, where the values are the median salary (in USD) for that country and job title.


In [120]:
# put your code here

filtered_df = salaries[salaries['employee_residence'].isin(
    filtered_counts.index)]


In [121]:
filtered_df


work_year experience_level employment_type                  job_title  \
0         2020               MI              FT             Data Scientist   
2         2020               SE              FT          Big Data Engineer   
4         2020               SE              FT  Machine Learning Engineer   
5         2020               EN              FT               Data Analyst   
6         2020               SE              FT        Lead Data Scientist   
..         ...              ...             ...                        ...   
602       2022               SE              FT              Data Engineer   
603       2022               SE              FT              Data Engineer   
604       2022               SE              FT               Data Analyst   
605       2022               SE              FT               Data Analyst   
606       2022               MI              FT               AI Scientist   

     salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0     70000             EUR          79833                 DE             0   
2     85000             GBP         109024                 GB            50   
4    150000             USD         150000                 US            50   
5     72000             USD          72000                 US           100   
6    190000             USD         190000                 US           100   
..      ...             ...            ...                ...           ...   
602  154000             USD         154000                 US           100   
603  126000             USD         126000                 US           100   
604  129000             USD         129000                 US             0   
605  150000             USD         150000                 US           100   
606  200000             USD         200000                 IN           100   

    company_location company_size quartiles  
0                 DE            L        Q2  
2                 GB            M        Q3  
4                 US            L        Q3  
5                 US            L        Q2  
6                 US            S        Q4  
..               ...          ...       ...  
602               US            M        Q4  
603               US            M        Q3  
604               US            M        Q3  
605               US            M        Q3  
606               US            L        Q4  

[506 rows x 12 columns]

In [122]:
pt2 = filtered_df.pivot_table(
    index="job_title", values="salary_in_usd", aggfunc="median", columns="employee_residence")


In [123]:
pt2


employee_residence                              CA        DE       ES  \
job_title                                                               
3D Computer Vision Researcher                  NaN       NaN      NaN   
AI Scientist                                   NaN       NaN  55000.0   
Analytics Engineer                             NaN       NaN      NaN   
Applied Data Scientist                         NaN       NaN      NaN   
Applied Machine Learning Scientist             NaN       NaN      NaN   
BI Data Analyst                                NaN       NaN      NaN   
Big Data Architect                         99703.0       NaN      NaN   
Big Data Engineer                              NaN       NaN  60000.0   
Business Data Analyst                      70912.0       NaN      NaN   
Computer Vision Engineer                       NaN       NaN      NaN   
Computer Vision Software Engineer              NaN   95746.0      NaN   
Data Analyst                               71786.0   63831.0  32974.0   
Data Analytics Engineer                        NaN   79197.0      NaN   
Data Analytics Lead                            NaN       NaN      NaN   
Data Analytics Manager                         NaN       NaN      NaN   
Data Architect                            141550.0       NaN      NaN   
Data Engineer                                  NaN   59985.0  76940.0   
Data Engineering Manager                       NaN   59303.0  79833.0   
Data Science Consultant                        NaN   76833.0      NaN   
Data Science Engineer                     127221.0       NaN      NaN   
Data Science Manager                           NaN       NaN      NaN   
Data Scientist                             81756.0   79833.0  38776.0   
Data Specialist                                NaN       NaN      NaN   
Director of Data Engineering                   NaN       NaN      NaN   
Director of Data Science                  196979.0  135936.0      NaN   
ETL Developer                                  NaN       NaN      NaN   
Finance Data Analyst                           NaN       NaN      NaN   
Financial Data Analyst                         NaN       NaN      NaN   
Head of Data                                   NaN       NaN      NaN   
Head of Data Science                           NaN       NaN      NaN   
Head of Machine Learning                       NaN       NaN      NaN   
Lead Data Analyst                              NaN       NaN      NaN   
Lead Data Engineer                        118187.0       NaN      NaN   
Lead Data Scientist                            NaN       NaN      NaN   
Lead Machine Learning Engineer                 NaN   87932.0      NaN   
ML Engineer                                    NaN   15966.0      NaN   
Machine Learning Developer                 78791.0       NaN      NaN   
Machine Learning Engineer                      NaN   59693.5  47282.0   
Machine Learning Infrastructure Engineer       NaN       NaN      NaN   
Machine Learning Manager                  117104.0       NaN      NaN   
Machine Learning Scientist                     NaN       NaN      NaN   
Marketing Data Analyst                         NaN       NaN      NaN   
NLP Engineer                                   NaN       NaN      NaN   
Principal Data Analyst                     75000.0       NaN      NaN   
Principal Data Engineer                        NaN       NaN      NaN   
Principal Data Scientist                       NaN  162674.0      NaN   
Product Data Analyst                           NaN       NaN      NaN   
Research Scientist                         96113.0       NaN      NaN   
Staff Data Scientist                           NaN       NaN      NaN   

employee_residence                             FR        GB       GR  \
job_title                                                              
3D Computer Vision Researcher                 NaN       NaN      NaN   
AI Scientist                                  NaN       NaN 

The pivot table above shows the median salary (in USD) among the country employee's reside and job title for countries that have at least 10 individuals in the data set. We see from the data set that there are many missing values. However, we can see where median salaries are particularly high or low. For example, we can see that a data analyst in India has the lowest median salary at $6,072. We can also see how salaries differ across countries for the same role. For example, a research scientist in France has a median salary of $59,693.5 while in the US it is $144,000.


## Please submit your completed notebook in .IPYNB and .HTML formats via Canvas


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f26867a0-b9e0-4d1a-8790-8e710ec3789a' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>
